<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\html_constructor\models;


use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "hc_draft_tag".
 *
 * @property integer $hc_draft_id
 * @property integer $hc_tag_id
 * @property integer $sort
 *
 * @property \common\html_constructor\models\HcDraft $hcDraft
 * @property \common\html_constructor\models\HcTag $hcTag
 * @property string $aliasModel
 */

class HcDraftTag extends \yii\db\ActiveRecord
{

    use \common\html_constructor\models\utility\SortableTrait;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return
            ArrayHelper::merge(
                [],
                $this->sortableModelBehavior()
            );
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hc_draft_tag';
    }

    public static function primaryKey()
    {
        return ['hc_draft_id', 'hc_tag_id'];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hc_draft_id', 'hc_tag_id', 'sort'], 'integer'],
            [['hc_draft_id', 'hc_tag_id'], 'unique', 'targetAttribute' => ['hc_draft_id', 'hc_tag_id']],
            [['hc_draft_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\html_constructor\models\HcDraft::class, 'targetAttribute' => ['hc_draft_id' => 'id']],
            [['hc_tag_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\html_constructor\models\HcTag::class, 'targetAttribute' => ['hc_tag_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'hc_draft_id' => Yii::t('models', 'Hc Draft ID'),
            'hc_tag_id' => Yii::t('models', 'Hc Tag ID'),
            'sort' => Yii::t('models', 'Sort'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHcDraft()
    {
        return $this->hasOne(\common\html_constructor\models\HcDraft::class, ['id' => 'hc_draft_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHcTag()
    {
        return $this->hasOne(\common\html_constructor\models\HcTag::class, ['id' => 'hc_tag_id']);
    }

}
