<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\html_constructor\models;


use Exception;
use Yii;

/**
 * This is the base-model class for table "hc_object_file_target".
 *
 * @property integer $id
 * @property integer $hc_object_id
 * @property string $type
 * @property integer $index
 *
 * @property \common\html_constructor\models\HcObjectFile[] $hcObjectFile
 * @property \common\html_constructor\models\HcObject $hcObject
 * @property string $aliasModel
 */
class HcObjectFileTarget extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hc_object_file_target';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['hc_object_id', 'index'], 'integer'],
            [['type'], 'string', 'max' => 255],
            [['hc_object_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\html_constructor\models\HcObject::class, 'targetAttribute' => ['hc_object_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'hc_object_id' => Yii::t('models', 'Site Object ID'),
            'type' => Yii::t('models', 'Type'),
            'index' => Yii::t('models', 'Index'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHcObjectFile()
    {
        return $this->hasMany(\common\html_constructor\models\HcObjectFile::class, ['file_target_id' => 'id'])->orderBy('sort ASC');
    }

    /** @return \common\html_constructor\models\File[] */
    public function getFileArray()
    {
        return array_map(function ($fileObj) {
            return $fileObj->file;
        }, $this->hcObjectFile);
    }

    /**
     * @return HcObjectFile
     * @throws Exception
     */
    public function attachFile($file)
    {
        $newFile = new HcObjectFile([
            'file_target_id' => $this->id,
            'file_id' => $file->id,
        ]);
        if ($newFile->save()) {
            return $newFile;
        } else throw new Exception("Не удалось закрепить файл за объектом");
    }

    public function beforeDelete()
    {
        $objectsToClean = $this->hcObjectFile;
        foreach ($objectsToClean as $object) {
            if (!$object->delete()) {
                return false;
            }
        }

        return parent::beforeDelete();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHcObject()
    {
        return $this->hasOne(\common\html_constructor\models\HcObject::class, ['id' => 'hc_object_id']);
    }
}
